site_name: Iterus.net Documentation
site_url: https://iterus.net
copyright: 'Copyright &copy; 2021-2022 Iterus.net'
markdown_extensions:
  - attr_list
  - md_in_html
theme:
  name: material
  font:
    text: Roboto
  palette:
    primary: teal
nav:
  - index.md
  - Setup:
    - setup/build.md
    - setup/deployment.md
  - Use:
    - Users:
      - users/calls.md
      - users/chat.md
      - users/popups.md
      - users/whiteboard.md